### ISSUE TITLE
Card Deck Support

### ISSUE THREAD

**Issue by divyanshu707** [martinbean/bootstrap-3-card#5]
Hi @martinbean 

Is there going to be card deck support any time soon ? 

Thanks

**Comment by martinbean** [comment]
@divyanshu707 Sure. I’ll add it hopefully some point today or if not, tomorrow.

**Comment by ghost** [comment]
Is this still a thing?

**Comment by mattcoker** [comment]
@martinbean Has there been any progress on this?

**Comment by adambedford** [comment]
This would be great to have. @martinbean Any updates?

**Comment by jlblcc** [comment]
:+1:

**Comment by martinbean** [comment]
I’m in two minds as to whether to implement this or not. The card deck implementation uses Flexbox, which Bootstrap 3 doesn’t support. This project was created just to scratch my own itch, and keen to maintain feature parity with Bootstrap 3, i.e. not introduce Flexbox dependencies when the rest of the library doesn’t make use of it.

**Comment by vimalmistry** [comment]
Just add in .sass file

```scss
$col-width: 16em; 
$col-gap: 1.5em;

.card-columns {
  -moz-column-width: $col-width;
  -webkit-column-width: $col-width;
  -moz-column-gap: $col-gap;
  -webkit-column-gap: $col-gap;
  .card {
    display: inline-block;
    padding: .10rem;
    width: 100%;
  }
}
```
